# Generated by Django 6.0.7 on 2026-07-17 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du bateau')),
                ('capacite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité (places)')),
                ('type_bateau', models.CharField(choices=[('VEDETTE', 'Vedette rapide'), ('FERRY', 'Ferry'), ('PIROGUE', 'Pirogue motorisée')], default='VEDETTE', max_length=20, verbose_name='Type')),
                ('en_service', models.BooleanField(default=True, verbose_name='En service')),
            ],
            options={
                'verbose_name': 'Bateau',
                'verbose_name_plural': 'Bateaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_depart', models.CharField(max_length=80, verbose_name='Port de départ')),
                ('port_arrivee', models.CharField(max_length=80, verbose_name="Port d'arrivée")),
                ('distance_km', models.PositiveIntegerField(verbose_name='Distance (km)')),
                ('duree_min', models.PositiveIntegerField(verbose_name='Durée du trajet (minutes)')),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
                'ordering': ['port_depart', 'port_arrivee'],
                'constraints': [models.UniqueConstraint(fields=('port_depart', 'port_arrivee'), name='ligne_unique_depart_arrivee')],
            },
        ),
        migrations.CreateModel(
            name='Traversee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure de départ')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FC)')),
                ('bateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traversees', to='reservations.bateau', verbose_name='Bateau')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traversees', to='reservations.route', verbose_name='Ligne')),
            ],
            options={
                'verbose_name': 'Traversée',
                'verbose_name_plural': 'Traversées',
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code du billet')),
                ('nom_passager', models.CharField(max_length=120, verbose_name='Nom du passager')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('nb_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total payé (FC)')),
                ('statut', models.CharField(choices=[('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='CONFIRME', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('traversee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.traversee', verbose_name='Traversée')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='traversee',
            constraint=models.UniqueConstraint(fields=('route', 'bateau', 'date', 'heure'), name='traversee_unique'),
        ),
    ]
