# Generated by Django 6.0.7 on 2026-07-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('MPESA', 'M-Pesa'), ('CARTE', 'Carte bancaire')], default='ORANGE_MONEY', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Paiement échoué'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=12, verbose_name='Statut'),
        ),
    ]
