# Generated by Django 6.0.7 on 2026-07-22 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_mode_paiement_alter_reservation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='billet_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Billet envoyé par e-mail'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail (pour recevoir le billet)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_comptoir', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par (agent guichet)'),
        ),
        migrations.AddField(
            model_name='traversee',
            name='alerte_remplissage_envoyee',
            field=models.BooleanField(default=False, editable=False, verbose_name='Alerte de remplissage déjà envoyée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('MPESA', 'M-Pesa'), ('CARTE', 'Carte bancaire'), ('ESPECES', 'Espèces (comptoir)')], default='ORANGE_MONEY', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
