# Generated by Django 6.0.7 on 2026-07-23 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_billet_envoye_reservation_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=30, unique=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('mot_de_passe', models.CharField(max_length=128, verbose_name='Mot de passe (haché)')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
            ],
            options={
                'verbose_name': 'Passager (compte)',
                'verbose_name_plural': 'Passagers (comptes)',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rappel_envoye',
            field=models.BooleanField(default=False, editable=False, verbose_name='Rappel de départ envoyé'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.passager', verbose_name='Compte passager'),
        ),
    ]
