# Generated by Django 5.2.17 on 2026-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_ports_embarquement_remboursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Paiement échoué'), ('ANNULE', 'Annulé'), ('EMBARQUE', 'Embarqué')], default='EN_ATTENTE', max_length=12, verbose_name='Statut'),
        ),
    ]
