# Generated by Django 5.2.17 on 2026-09-21 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code du billet')),
                ('nom_passager', models.CharField(max_length=120, verbose_name='Nom du passager')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('nb_places', models.PositiveIntegerField(verbose_name='Nombre de places')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total payé (FC)')),
                ('mode_paiement', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('MPESA', 'M-Pesa'), ('CARTE', 'Carte bancaire'), ('ESPECES', 'Espèces (comptoir)')], max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Paiement échoué'), ('ANNULE', 'Annulé'), ('EMBARQUE', 'Embarqué')], max_length=12, verbose_name='Statut final')),
                ('date_creation', models.DateTimeField(verbose_name='Réservé le')),
                ('expire_le', models.DateTimeField(blank=True, null=True, verbose_name='Paiement avant')),
                ('embarquement_le', models.DateTimeField(blank=True, null=True, verbose_name='Embarqué le')),
                ('valide_par', models.CharField(blank=True, max_length=80, verbose_name='Validé par')),
                ('rembourse_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total remboursé (FC)')),
                ('archive_le', models.DateTimeField(auto_now_add=True, verbose_name='Archivé le')),
                ('archive_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
                ('traversee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='reservations.traversee', verbose_name='Traversée')),
            ],
            options={
                'verbose_name': 'Réservation archivée',
                'verbose_name_plural': 'Réservations archivées',
                'ordering': ['-archive_le'],
            },
        ),
    ]
