# Generated by Django 5.2.17 on 2026-09-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_historique_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='archivee',
            field=models.BooleanField(db_index=True, default=False, help_text='Masquée de la liste Django admin, mais le passager garde accès à son billet.', verbose_name="Archivée (cachée de l'admin)"),
        ),
        migrations.CreateModel(
            name='RecompenseFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code de récompense')),
                ('telephone', models.CharField(db_index=True, max_length=30, verbose_name='Téléphone du passager')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de la récompense')),
                ('seuil', models.PositiveIntegerField(default=10, verbose_name='Voyages atteints')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Offert le')),
                ('envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='E-mail envoyé le')),
                ('utilisee', models.BooleanField(default=False, verbose_name='Récompense utilisée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (usage du code...)')),
            ],
            options={
                'verbose_name': 'Récompense fidélité',
                'verbose_name_plural': 'Récompenses fidélité',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('telephone', 'seuil'), name='fidelite_unique_seuil')],
            },
        ),
        migrations.CreateModel(
            name='NotificationInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIDELITE', 'Fidélité'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=12, verbose_name='Type')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('detail', models.TextField(blank=True, verbose_name='Détail')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone concerné')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('recompense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.recompensefidelite', verbose_name='Récompense liée')),
            ],
            options={
                'verbose_name': 'Notification interne',
                'verbose_name_plural': 'Notifications internes',
                'ordering': ['-cree_le'],
            },
        ),
    ]
